"""Correlation-based metrics for LLM-as-Judge evaluation."""

from scipy.stats import spearmanr, pearsonr

def spearman_correlation(llm_scores, human_scores):
    """
    Calculate Spearman's rank correlation between LLM and human scores.
    
    Args:
        llm_scores (array-like): Scores generated by the LLM
        human_scores (array-like): Scores provided by human evaluators
        
    Returns:
        float: Spearman correlation coefficient
        float: p-value
    """
    return spearmanr(llm_scores, human_scores)

def pearson_correlation(llm_scores, human_scores):
    """
    Calculate Pearson correlation between LLM and human scores.
    
    Args:
        llm_scores (array-like): Scores generated by the LLM
        human_scores (array-like): Scores provided by human evaluators
        
    Returns:
        float: Pearson correlation coefficient
        float: p-value
    """
    return pearsonr(llm_scores, human_scores) 